#!/bin/bash
FILE=bin/memoria
mkdir -p logs
make clean
make
if test -f "./$FILE"; then
    valgrind --tool=memcheck --leak-check=yes --show-possibly-lost=yes --show-reachable=yes --num-callers=20 --track-origins=yes ./$FILE
fi