#!/bin/bash
FILE=bin/kernel
make clean
make
if test -f "./$FILE"; then
    valgrind --tool=memcheck --leak-check=yes --show-possibly-lost=no --show-reachable=no --num-callers=20  --track-origins=yes ./$FILE
fi